version: '3.9'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: &db_password '60000p-70000p'
      MYSQL_USER: &db_user 'nurdermind'
      MYSQL_PASSWORD: *db_password
      MYSQL_DATABASE: &db_name "uptrader_db"
    networks:
      - local
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 10s
      retries: 3
  server:
    build:
      context: server
      dockerfile: ./Dockerfile
    networks:
      - local
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - static_volume:/web/static
      - media_volume:/web/media
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    command: bash start.sh
    restart: on-failure
    environment:
      MYSQL_HOST: db
      MYSQL_USER: *db_user
      MYSQL_PASSWORD: *db_password
      MYSQL_DATABASE: *db_name

      DJANGO_SUPERUSER_EMAIL: 'admin@django.ru'
      DJANGO_SUPERUSER_USERNAME: 'admin'
      DJANGO_SUPERUSER_PASSWORD: 'admin'
    volumes:
      - ./web:/web
      - static_volume:/web/static
      - media_volume:/web/media
    ports:
      - "8001:8000"
    networks:
      - local
    depends_on:
      db:
        condition: service_healthy

    healthcheck:
      test: [ "CMD", "ping", "-c", "1", "localhost:80" ]
      interval: 5s
      timeout: 10s
      retries: 3

networks:
  local:
volumes:
  static_volume:
  media_volume: